---
driver:
  name: rackspace
  public_key_path: ~/.ssh/id_rsa.pub
  rackspace_region: 'IAD'
  flavor_id: 'general1-2'

driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[nodejs]
  - name: iojs
    run_list:
      - recipe[nodejs]
    attributes:
      nodejs:
        fork: 'iojs'
