driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6.8
  - name: centos-7.3
  - name: debian-7.11
    run_list: apt::default
  - name: debian-8.7
    run_list: apt::default
  - name: fedora-25
  - name: opensuse-leap-42.2
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
- name: default
  run_list:
  - recipe[nodejs]
- name: package
  run_list:
  - recipe[test::package]
- name: binary
  run_list:
  - recipe[test::binary]
- name: source
  run_list:
  - recipe[test::source]
  excludes:
    - centos-6.8
- name: source-iojs
  run_list:
  - recipe[source_iojs]
  excludes:
    - centos-6.8
- name: npm
  run_list:
  - recipe[test::npm]
- name: npm_embedded
  run_list:
  - recipe[test::npm]
  attributes:
    nodejs:
      npm:
        install_method: embedded
- name: npm_source
  run_list:
  - recipe[test::npm]
  attributes:
    nodejs:
      npm:
        install_method: source
  excludes:
    - centos-6.8
- name: npm_packages
  run_list: recipe[nodejs]
  attributes:
    nodejs:
      npm_packages:
        - name: express
        - name: socket.io
          version: 1.0.4
        - name: express
          action: uninstall
